### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by wenchangzhou** [Lackel/DPN#2]
hi wenbin:
感谢贡献非常出色的工作，有一些疑问还麻烦解答一下，感谢：
1、https://github.com/Lackel/DPN/blob/b359340c4feacc0758e66c153ba92c4db8ab0100/DPN.py#L143
这里不应该是计算Unlabeled prototypes吗？为什么这里用的是data.train_semi_dataloader？
2、代码中的超参数和论文中给出超参数为什么不一致呢？比如gamma_list、temperature、momentum_factor等等

**Comment by Lackel** [comment]
感谢您对我们工作的关注！
1. 在Unlabeled prototypes计算中加入了labeled data主要是为了更一般化地满足’所有的已知类别都要出现在未标注数据中‘这个假设；同时我们可以更加充分地利用这部分标注数据来辅助prototypes的对齐。另外，由于在计算Unlabeled prototypes时我们并没有利用这部分标注数据的标签，因此我们把semi_dataloader (也就是全部训练数据) 称为unlabelled data，同时并不违背GCD的任务设置和我们模型的设计初衷。
2. 由于我们的代码之前出现了一些bug，因此我们重新进行了部分实验，并更新了超参数和实验结果，我们在提交给AAAI的最终版中已经包含了这些更新，但Arxiv版本还没有来得及更新，我们随后会对Arxiv上的论文也进行更新。
再次感谢您对我们的工作感兴趣！

**Comment by wenchangzhou** [comment]
感谢wenbin的详细解答，另外：
1、请问实验中数据集的划分和设置是和[1]完全对齐的吗？
2、期待尽快能在arXiv上看到最新的更新版本；

[1] Discovering New Intents with Deep Aligned Clustering-AAAI2021

**Comment by Lackel** [comment]
感谢您的关注！
1. 数据集划分和设置是和1是相同的。
2. 新的Arxiv版本已经上传了，明天应该就可以看到了。
