### ISSUE TITLE
self.predict_k(args, data)  is not defined in the code for args.cluster_num_factor > 1:

### ISSUE THREAD

**Issue by Chandan-IITI** [Lackel/DPN#3]
It seems self.predict_k(args, data)  is not defined in the code (line numbers 32 and 33 in DPN.py) for args.cluster_num_factor > 1: (https://github.com/Lackel/DPN/blob/main/DPN.py#L33)

`        if args.cluster_num_factor > 1:
            self.num_labels = self.predict_k(args, data) `

**Comment by Lackel** [comment]
Hi, we have added this function to our code. You can check it now.

**Comment by Chandan-IITI** [comment]
Thanks. now code is working

**Comment by Chandan-IITI** [comment]
Thanks. now code is working
